# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: development_db
  pool: 5
  timeout: 5000
  username: thomas
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  timeout: 5000
  username: thomas
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: production_db
  pool: 5
  timeout: 5000
  username: thomas
  password: